name=input('what is your name:')
age=int(input('what is your age:'))
height=float(input('what is your height:'))
print('Your name is '+name)
print('You are '+str(age)+' years old')
print('You are '+str(height)+' tall')